package com.emmkay.infertility_system.modules.email.enums;

public enum EmailType {

    OTP_VERIFICATION,
    REMINDER_APPOINTMENT,
    REGISTER_SERVICE,
    RECORD_SUCCESS,
    RECORD_CANCEL,
    APPOINTMENT_CHANGE_DOCTOR_MANAGER,
    APPOINTMENT_CHANGE_CUSTOMER,
    APPOINTMENT_CHANGE_SUCCESS,
    APPOINTMENT_CHANGE_FAIL,
    APPOINTMENT_AUTO_REVERT,
    PAYMENT_SUCCESS,
}
