export const path = {
  homePage: "/",
  pageNotFound: "*",
  signUp: "/sign-up",
  signIn: "/sign-in",
  testLogin: "/dang-nhap",
  verify: "/verify-otp",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  services: "/services",
  serviceDetail: "/service-detail/:serviceId",
  blog: "/blog",
  blogDetail: "/blog/:blogSlug",
  ourStaff: "/doctor",
  features: "/features",
  contacts: "/contacts",
  doctorDetail: "/doctors/detail/:id",
  appointment: "/register-service",
  admin: "/admin",

  // Manager routes
  manager: "/manager/",
  managerDashboard: "/manager/dashboard",
  managerStaff: "/manager/staff",
  managerServices: "/manager/services",
  managerAppointments: "/manager/appointments",
  managerPatients: "/manager/patients",
  managerReports: "/manager/reports",
  managerRenderCreateTreatmentService: "/manager/create-treatment-service",

  // Doctor routes
  doctor: "/doctor-dashboard/",
  doctorDashboard: "/doctor-dashboard/dashboard",
  doctorAppointments: "/doctor-dashboard/appointments",
  doctorPatients: "/doctor-dashboard/patients",
  doctorSchedule: "/doctor-dashboard/schedule",
  doctorTestResults: "/doctor-dashboard/test-results",
  doctorProfile: "/doctor-dashboard/profile",
  doctorWorkSchedule: "/doctor-dashboard/work-schedule",
  doctorTreatmentStages: "/doctor-dashboard/treatment-stages",
  doctorChangeRequests: "/doctor-dashboard/change-requests",

  // Customer routes
  customer: "/customer-dashboard/",
  customerProfile: "/customer-dashboard/profile",
  customerServices: "/customer-dashboard/services",
  customerAppointments: "/customer-dashboard/appointments",
  customerTreatment: "/customer-dashboard/treatment",
  customerReviews: "/customer-dashboard/reviews",
  customerNotifications: "/customer-dashboard/notifications",
  customerFeedback: "/customer-dashboard/feedback",
  customerMedicalRecord: "/customer-dashboard/medical-record",
  customerPayment: "/customer-dashboard/payment",
  customerUpdateProfile: "/customer-dashboard/update-profile",

  updataProfile: "/update-profile",
  resendOtp: "/resend-otp",
  payment: "/payment",
};
